max_num_patients: 100 #
batch_size: 1
K: 1562 # points per label
pool_size: 8 # avg pooling dimension in coordinate head 
hidden_coord: 256
enable_deep_supervision: false
number_frames : 20

is_ddp: false
cuda_device_index: 0

fold: "all" #
dataset_folder: /home/renku/work/s3-bucket/cardiac_deformation_final_dataset

initial_lr: 0.001
weight_decay: 0.00003
oversample_foreground_percent: 0.0
probabilistic_oversampling: false
num_train_iterations_per_epoch: 250
num_val_iterations_per_epoch: 50
num_epochs: 50 #
current_epoch: 0
ld_checkpoint : true
tr_checkpoint_path : /home/renku/work/s3-bucket/OUTPUTS/unet_coord_runs/2026-06-03_09-38-00/checkpoint_latest.pth 
tr_checkpoint_path_best : /home/renku/work/s3-bucket/OUTPUTS/unet_coord_runs/2026-06-03_09-38-00/checkpoint_best.pth
save_every: 1
disable_checkpointing: false
checkpoint_path: /home/renku/work/s3-bucket/nnUNet_results_0/Dataset027_ACDC/nnUNetTrainer_100epochs__nnUNetPlans__3d_fullres/fold_0/checkpoint_best.pth
history_json: training_history.json

alpha_1: 0.2 #smoothing parameter losses
alpha_2: 0.1 #smoothing parameter euclidean error

hydra:
  job:
    name: unet_coord_debug
    chdir: true
  run:
    dir: /home/renku/work/s3-bucket/OUTPUTS/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}