


checkpoint_path : /home/renku/work/s3-bucket/OUTPUTS/unet_coord_runs/2026-05-29_13-40-27/checkpoint_best.pth #
batch_size : 1
K: 1562 # points per label
pool_size: 2 # avg pooling in coordinate head 
hidden_coord: 256


dataset:
  _target_: src.datasets.inference_coord_dataset.nnUNetDatasetCoordTest
  folder: /home/renku/work/s3-bucket/cardiac_deformation_final_dataset
  max_num_patients: 80
  max_num_patients_test: 10
  num_frames_per_patient: 20

loss:
  _target_: torch.nn.HuberLoss
  reduction: none
  delta: 0.05


hydra:
  job:
    name: unet_coord_test
    chdir: true
  run:
    dir: /home/renku/work/s3-bucket/OUTPUTS/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}