acdc_training_root: /home/renku/work/s3-bucket/ACDC
test_dir: /home/renku/work/test_dir_interpolated_frames
target_length: 20
clear_inference_input_dir: true
save_interpolation_metadata: true
script:
  path: /home/renku/work/Cardiac-Deformation-SDSC/run_inference_u_net.sh
set_test : false