max_num_patients: 10
batch_size: 1
K: 1562 # points per label
pool_size: 3 # avg pooling in coordinate head 
hidden_coord: 256
enable_deep_supervision: false

is_ddp: false
cuda_device_index: 0

fold: 0
dataset_folder: /home/renku/work/cardiac_deformation_final_dataset

initial_lr: 0.01
weight_decay: 0.00003
oversample_foreground_percent: 0.33
probabilistic_oversampling: false
num_train_iterations_per_epoch: 5
num_val_iterations_per_epoch: 1
num_epochs: 10
current_epoch: 0

save_every: 1
disable_checkpointing: false
checkpoint_path: /home/renku/work/nnUNet_results_0/Dataset027_ACDC/nnUNetTrainer_100epochs__nnUNetPlans__3d_fullres/fold_0/checkpoint_best.pth
history_json: training_history.json

hydra:
  job:
    name: unet_coord_runs
    chdir: true
  run:
    dir: /home/renku/work/OUTPUTS/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}